version: '3'

services: 
  db: 
    image: "postgres"
    ports:
      - "5432:5432"
    networks:
      - db_nw
    environment: 
      - POSTGRES_USER=paracord
      - POSTGRES_PASSWORD=paracord
  web: 
    build: .
    volumes:
      - .:/app
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db 
    env_file:
      - ./.docker/web.env
    environment:
      - DB_HOST=db
      - DB_NAME=paracord
      - DB_USER=paracord
      - DB_PASS=paracord
  nginx:
    image: "nginx"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./.docker/conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on:
      - web
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
