version: '3'

services: 
  paracord_db: 
    image: "postgres"
    ports:
      - "5432:5432"
    networks:
      - paracord_db_nw
    environment: 
      - POSTGRES_USER=paracord
      - POSTGRES_PASSWORD=paracord
  
  paracord_web: 
    build: .
    volumes:
      - .:/web
      - paracord_node_modules:/web/node_modules
      - paracord_bin:/web/bin
    ports: 
      - "80:3000"
    networks:
      - paracord_web_nw
      - paracord_db_nw
    depends_on: 
      - paracord_db

networks:
  paracord_web_nw:
    driver: bridge
  paracord_db_nw:
    driver: bridge

volumes: 
  paracord_node_modules:
  paracord_bin:
