version: '3'

services: 
  paracord_db: 
    image: "postgres"
    ports:
      - "5432:5432"
    networks:
      - paracord_db_nw
    environment: 
      - POSTGRES_USER=paracord
      - POSTGRES_PASSWORD=paracord
  paracord_web: 
    build: .
    restart: always
    volumes:
      - .:/app
    networks:
      - paracord_db_nw
      - paracord_web_nw
    depends_on:
      - paracord_db
    env_file:
      - ./.docker/web.env
    environment:
      - DB_HOST=paracord_db
      - DB_NAME=paracord
      - DB_USER=paracord
      - DB_PASS=paracord
  paracord_nginx:
    image: "nginx"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./.docker/conf.d:/etc/nginx/conf.d
    networks:
      - paracord_web_nw
    depends_on:
      - paracord_web
networks:
  paracord_db_nw:
    driver: bridge
  paracord_web_nw:
    driver: bridge
